[package]
name = "2d-engine"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge.aparicio.pomona.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
